/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "pjbdislsarrikfmfvtqm"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqYmRpc2xzYXJyaWtmbWZ2dHFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc1NDU3MjMsImV4cCI6MjA4MzEyMTcyM30.cnNChKG9vXJhJdxTPanlk7Y-0Z-lm2HAY_PQfwBmpjw"